# Build 설정
[build]
  publish = "dist"                # 빌드된 정적 파일 경로 (일반적으로 build 또는 dist)
  functions = "netlify/functions" # Netlify 서버리스 함수들이 위치하는 경로

# API 호출을 서버리스 함수로 리디렉션
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# SPA 리디렉션 설정: 404 방지를 위해 모든 경로를 index.html로 리디렉트
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Netlify Dev 설정: 로컬 개발 환경에서 Netlify CLI를 사용할 때
[dev]
  framework = "#custom"            # 사용할 프레임워크 (React, Vue 등 자동 감지 가능)
  command = "npm run dev"          # 로컬에서 개발 서버를 실행하는 명령어
  targetPort = 8080                # 개발 서버의 포트
  port = 8888                      # Netlify Dev가 사용할 포트
  publish = "dist"                 # 정적 파일 경로
  autoLaunch = false               # 로컬 개발 시 자동으로 브라우저를 열지 않음
