[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[dev]  
  framework = "#custom"         # 감지할 프로젝트 유형을 지정합니다. 앱 서버 및 'targetPort' 옵션을 실행하는 명령 옵션은 ''
  command = "npm run dev"       # 연결할 프로젝트의 개발 서버를 실행하는 명령(스크립트)을 지정합니다.
  targetPort = 8080             # 연결할 프로젝트 개발 서버의 포트를 지정합니다.
  port = 8888
  publish = "dist"              # 프로젝트의 정적 콘텐츠 디렉토리를 지정합니다.
  autoLaunch = false            # Netlify 서버가 준비되면 자동으로 브라우저를 오픈할 것인지 지정합니다.